# Generated by Django 5.2.1 on 2025-05-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneasy_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
