# Generated by Django 5.2.1 on 2025-06-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneasy_api', '0003_alter_user_birth_date_alter_user_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='income_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
